"""FastAPI service for Pipeworks entity state generation.

This module exposes HTTP endpoints around the existing `condition_axis` library.
It keeps API behavior intentionally thin:

1. Validate request payloads with Pydantic models.
2. Delegate generation logic to the library.
3. Return JSON payloads in a stable structure.

The service is designed to be reverse-proxied by Nginx and run under systemd.
"""

from __future__ import annotations

import random
from hashlib import sha256
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as package_version
from typing import Any

from fastapi import FastAPI
from pydantic import BaseModel, ConfigDict, Field

from condition_axis import (
    __version__ as condition_axis_version,
)
from condition_axis import (
    condition_to_prompt,
    generate_condition,
    generate_occupation_condition,
    get_available_axes,
    get_available_occupation_axes,
    get_axis_values,
    get_occupation_axis_values,
    occupation_condition_to_prompt,
)

app = FastAPI(title="Pipeworks Entity State API", version="0.1.0")

GENERATOR_PACKAGE_NAME = "pipeworks-conditional-axis"
GENERATOR_CAPABILITIES = [
    "character_conditions",
    "occupation_conditions",
    "seeded_generation",
    "numeric_axis_scores",
    "prompt_serialization",
]
DEFAULT_AXIS_PROFILE = "character_full"
LEGACY_AXIS_PROFILE = "subset_legacy"


def _resolve_generator_version() -> str:
    """Resolve the generator version for adapter-facing metadata."""

    try:
        return package_version(GENERATOR_PACKAGE_NAME)
    except PackageNotFoundError:
        # Fallback keeps metadata available in non-installed contexts.
        return str(condition_axis_version)


GENERATOR_VERSION = _resolve_generator_version()


class EntityRequest(BaseModel):
    """Request payload for generating a single entity.

    `seed` is optional. If omitted, the API generates a random replayable seed.
    `include_prompts` controls whether prompt-form strings are included.
    """

    model_config = ConfigDict(extra="forbid")
    seed: int | None = Field(default=None)
    include_prompts: bool = True
    axis_profile: str = Field(
        default=DEFAULT_AXIS_PROFILE,
        pattern=f"^({DEFAULT_AXIS_PROFILE}|{LEGACY_AXIS_PROFILE})$",
        description=(
            "Axis profile used for generation. "
            "'character_full' returns the full canonical character+occupation axis set; "
            "'subset_legacy' preserves historical sparse optional-axis behavior."
        ),
    )


class BatchRequest(BaseModel):
    """Request payload for generating multiple entities.

    `start_seed` sets the first deterministic seed in the sequence.
    `count` is bounded to protect service health.
    `include_prompts` controls whether each entity includes prompt strings.
    """

    model_config = ConfigDict(extra="forbid")
    start_seed: int = 0
    count: int = Field(default=10, ge=1, le=500)
    include_prompts: bool = True
    axis_profile: str = Field(
        default=DEFAULT_AXIS_PROFILE,
        pattern=f"^({DEFAULT_AXIS_PROFILE}|{LEGACY_AXIS_PROFILE})$",
        description=(
            "Axis profile used for each generated entity. "
            "'character_full' returns the full canonical character+occupation axis set; "
            "'subset_legacy' preserves historical sparse optional-axis behavior."
        ),
    )


def _ordinal_score_from_values(value: str, ordered_values: list[str]) -> float | None:
    """Map one ordinal label to a normalized score in ``[0, 1]``.

    Args:
        value: Selected label value for one axis.
        ordered_values: Canonical low-to-high label ordering for that axis.

    Returns:
        Deterministic normalized score, or ``None`` when value is unknown.
    """

    if not ordered_values:
        return None

    try:
        index = ordered_values.index(value)
    except ValueError:
        return None

    if len(ordered_values) == 1:
        return 0.5
    return index / (len(ordered_values) - 1)


def _build_numeric_axes(
    *,
    character: dict[str, str],
    occupation: dict[str, str],
) -> dict[str, dict[str, float | str]]:
    """Build canonical numeric axis scores alongside label outputs.

    The API preserves existing ``character``/``occupation`` label blocks while
    adding this numeric ``axes`` block for adapter compatibility.

    Args:
        character: Character axis labels generated by ``generate_condition``.
        occupation: Occupation axis labels generated by ``generate_occupation_condition``.

    Returns:
        Axis-name keyed map containing ``label`` and normalized ``score``.
    """

    axes: dict[str, dict[str, float | str]] = {}

    for axis_name, label in character.items():
        if not isinstance(label, str):
            continue
        score = _ordinal_score_from_values(label, get_axis_values(axis_name))
        if score is None:
            continue
        axes[axis_name] = {"label": label, "score": score}

    for axis_name, label in occupation.items():
        if not isinstance(label, str):
            continue
        score = _ordinal_score_from_values(label, get_occupation_axis_values(axis_name))
        if score is None:
            continue
        axes[axis_name] = {"label": label, "score": score}

    return axes


def _deterministic_full_axis_value(*, seed: int, axis_name: str, values: list[str]) -> str:
    """Select one axis label deterministically from ordered axis values.

    Args:
        seed: Deterministic seed used for payload generation.
        axis_name: Axis key (including group prefix for uniqueness).
        values: Canonical ordered value list for the axis.

    Returns:
        Deterministically selected axis label.

    Raises:
        ValueError: If values list is empty.
    """
    if not values:
        raise ValueError(f"Axis {axis_name!r} has no values.")

    digest = sha256(f"{seed}:{axis_name}".encode()).digest()
    index = int.from_bytes(digest[:8], byteorder="big", signed=False) % len(values)
    return values[index]


def _build_entity(
    seed: int,
    include_prompts: bool,
    axis_profile: str,
) -> dict[str, Any]:
    """Build one entity payload from library generators.

    Args:
        seed: Deterministic seed used by generation functions.
        include_prompts: Whether to attach serialized prompt strings.

    Returns:
        Response-ready dictionary for one entity.
    """
    # Generate both axis systems from the same seed so payloads are
    # reproducible and easy to reference/debug by seed.
    if axis_profile == LEGACY_AXIS_PROFILE:
        character = generate_condition(seed=seed)
        occupation = generate_occupation_condition(seed=seed)
    else:
        character = {
            axis_name: _deterministic_full_axis_value(
                seed=seed,
                axis_name=f"character:{axis_name}",
                values=get_axis_values(axis_name),
            )
            for axis_name in get_available_axes()
        }
        occupation = {
            axis_name: _deterministic_full_axis_value(
                seed=seed,
                axis_name=f"occupation:{axis_name}",
                values=get_occupation_axis_values(axis_name),
            )
            for axis_name in get_available_occupation_axes()
        }

    # Keep response schema explicit and stable for frontend/API consumers.
    payload: dict[str, Any] = {
        "seed": seed,
        "axis_profile": axis_profile,
        "character": character,
        "occupation": occupation,
        "axes": _build_numeric_axes(character=character, occupation=occupation),
    }

    # Prompts are optional because some clients only want structured axis data.
    if include_prompts:
        character_prompt = condition_to_prompt(character)
        occupation_prompt = occupation_condition_to_prompt(occupation)
        payload["prompts"] = {
            "character": character_prompt,
            "occupation": occupation_prompt,
            "full": f"{character_prompt}, {occupation_prompt}",
        }
    return payload


def _resolve_seed(requested_seed: int | None) -> int:
    """Resolve a request seed into a concrete integer.

    Args:
        requested_seed: User-provided seed or ``None``.

    Returns:
        A concrete seed integer for generation.
    """
    # If the caller sends a seed, preserve it exactly for deterministic output.
    if requested_seed is not None:
        return requested_seed

    # For unseeded requests, generate a broad-range positive integer so clients
    # can store/replay the returned seed later if desired.
    return random.SystemRandom().randrange(0, 2_147_483_647)


@app.get("/health")
@app.get("/api/health")
async def health() -> dict[str, str]:
    """Health endpoint for load balancers and monitoring systems.

    Returns:
        A minimal status object proving process responsiveness.
    """

    return {"status": "ok", "service": "pipeworks-entity-state-api"}


@app.get("/api/axes")
async def axes() -> dict[str, Any]:
    """Return available axes and values for all supported generation systems.

    Returns:
        Nested dictionary with axis names and permitted values for:
        - character state generation
        - occupation state generation
    """

    # Pull canonical definitions from the library so this endpoint always
    # mirrors the actual generator configuration.
    character_axes = get_available_axes()
    occupation_axes = get_available_occupation_axes()
    return {
        "character": {
            "axes": character_axes,
            "values": {axis: get_axis_values(axis) for axis in character_axes},
        },
        "occupation": {
            "axes": occupation_axes,
            "values": {axis: get_occupation_axis_values(axis) for axis in occupation_axes},
        },
    }


@app.post("/api/entity")
async def generate_entity(req: EntityRequest) -> dict[str, Any]:
    """Generate one entity state payload.

    Args:
        req: Parsed request body.

    Returns:
        One generated entity, optionally with prompt strings.
    """
    seed = _resolve_seed(req.seed)
    payload = _build_entity(
        seed=seed,
        include_prompts=req.include_prompts,
        axis_profile=req.axis_profile,
    )
    payload["generator_version"] = GENERATOR_VERSION
    payload["generator_capabilities"] = list(GENERATOR_CAPABILITIES)
    return payload


@app.post("/api/entities/batch")
async def generate_entities(req: BatchRequest) -> dict[str, Any]:
    """Generate a sequential batch of entity state payloads.

    Args:
        req: Parsed batch request body.

    Returns:
        A dictionary containing metadata plus generated entities.
    """

    # Use sequential seeds to make batch generation deterministic and simple to
    # replay (start_seed + index for each element).
    entities = [
        _build_entity(
            seed=req.start_seed + index,
            include_prompts=req.include_prompts,
            axis_profile=req.axis_profile,
        )
        for index in range(req.count)
    ]
    return {
        "start_seed": req.start_seed,
        "count": req.count,
        "axis_profile": req.axis_profile,
        "entities": entities,
    }
